//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ascentis.ExternalCache.TesterConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ascentis.ExternalCache.TesterConsole.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1,&quot;New Employee No Shift Associated        &quot;,1,1,7,NULL,00:00,23:59,0,1439,1,0,21,0.00,0.00,0.00,0.00,0,0,0,0,1,2,1,2,1,&quot;                                        &quot;,0,0,0,0,0.00,&quot;NEUADMIN  &quot;,2014-11-04 08:28:51.000,1,15,20,2,0,2,0,180,0,0,0,0.00,0,0,0,0,0,1,LREIMBNOLM=.F. LMEALOUTWKHRS=.F. LREIMPC=.F. NREIMPC=0 CREIMPCREF=00:00,0,0,0,0,0,0,NULL,0.00,0,NULL,0.00,0.00,0.00,0.00
        ///5,400,&quot;04:00 - 12:30 M-F M30                   &quot;,2,1,7,NULL,00:00,23:59,0,1439,1,0,21,6.00,0.00,0.00,0.00,30,0,0,0,1,2,1,2,1,&quot;       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleXML {
            get {
                return ResourceManager.GetString("SampleXML", resourceCulture);
            }
        }
    }
}
